export const mimeTypes = {
	video: {
		mp4: "video/mp4",
		webm: "video/webm",
		mkv: "video/x-matroska",
		mov: "video/quicktime",
		avi: "video/x-msvideo",
		flv: "video/x-flv",
		ts: "video/MP2T",
		ogv: "video/ogg",
		asf: "video/x-ms-asf",
		"3gp": "video/3gpp",
		rm: "application/vnd.rn-realmedia",
	},
	audio: {
		mp3: "audio/mpeg",
		wav: "audio/x-wav",
		aac: "audio/aac",
		flac: "audio/flac",
		ogg: "audio/ogg",
		m4a: "audio/mp4",
		wma: "audio/x-ms-wma",
		amr: "audio/amr",
		opus: "audio/opus",
	},
	text: {
		plain: "text/plain",
		html: "text/html",
		css: "text/css",
		javascript: "application/javascript",
		json: "application/json",
		xml: "application/xml",
		csv: "text/csv",
		markdown: "text/markdown",
		yaml: "application/x-yaml",
		pdf: "application/pdf",
		rtf: "application/rtf",
	},
	image: {
		png: "image/png",
		jpeg: "image/jpeg",
		jpg: "image/jpeg",
		gif: "image/gif",
		svg: "image/svg+xml",
		webp: "image/webp",
		bmp: "image/bmp",
		tiff: "image/tiff",
		ico: "image/x-icon",
	},
	documents: {
		pdf: "application/pdf",
		doc: "application/msword",
		docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		xls: "application/vnd.ms-excel",
		xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		ppt: "application/vnd.ms-powerpoint",
		pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	},
} as const;

export const mimeTypesObject = {
	...mimeTypes.audio,
	...mimeTypes.documents,
	...mimeTypes.image,
	...mimeTypes.text,
	...mimeTypes.video,
} as const;
